name: Build Debian Package

on: push

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        arch: ['amd64', 'arm64', 'armhf']
        include:
          - run-piuparts: false
          - run-piuparts: true
            arch: amd64
    uses: torizon/torizon-deb-ci/.github/workflows/toradex-deb-ci.yml@v0
    with:
      arch: ${{ matrix.arch }}
      distribution: bookworm
      docker-image: debian:bookworm
      package-name: weston
      run-attestation: true
      run-piuparts: "${{ matrix.run-piuparts }}"
      upload-artifacts: true
